CREATE TABLE saved_file (
  id INTEGER PRIMARY KEY NOT NULL,
  uuid CHARACTER VARYING NOT NULL,
  real_name CHARACTER VARYING NOT NULL,
  created TIMESTAMP WITH TIME ZONE NOT NULL,
  cdm_version FLOAT NOT NULL,
  is_deleted BOOLEAN DEFAULT (FALSE)
);

CREATE SEQUENCE saved_file_id_seq;