CREATE OR REPLACE FUNCTION import_tables(
)
  RETURNS VOID AS
$body$
BEGIN

  CREATE TABLE VOCABULARY_CONVERSION_TEMP
  (
    VOCABULARY_ID_V4 BIGINT,
    VOCABULARY_ID_V5 VARCHAR(20),
    OMOP_REQ         VARCHAR(1),
    CLICK_DEFAULT    VARCHAR(1),
    AVAILABLE        VARCHAR(25),
    URL              VARCHAR(256),
    CLICK_DISABLED   VARCHAR(1),
    LATEST_UPDATE    DATE
  );
  COPY VOCABULARY_CONVERSION_TEMP FROM '/home/athena_vocab_loader/v5_vocabulary_conversion.csv' DELIMITER ',' CSV HEADER;

  ALTER TABLE VOCABULARY_CONVERSION_TEMP ADD COLUMN name VARCHAR DEFAULT '';

  CREATE TABLE vocabulary_temp (
    vocabulary_id         VARCHAR(20)  NOT NULL,
    vocabulary_name       VARCHAR(255) NOT NULL,
    vocabulary_reference  VARCHAR(255) NULL,
    vocabulary_version    VARCHAR(255) NULL,
    vocabulary_concept_id INTEGER      NOT NULL
  );

  COPY vocabulary_temp FROM '/home/athena_vocab_loader/v5_vocabulary.csv' DELIMITER ',' CSV HEADER;

  UPDATE VOCABULARY_CONVERSION_TEMP vct
  SET NAME = vt.vocabulary_name
  from vocabulary_temp as vt where vct.VOCABULARY_ID_V5 LIKE vt.vocabulary_id;

  UPDATE VOCABULARY_CONVERSION vc
  SET VOCABULARY_ID_V4 = VOCABULARY_CONVERSION_TEMP.VOCABULARY_ID_V4,
    VOCABULARY_ID_V5   = VOCABULARY_CONVERSION_TEMP.VOCABULARY_ID_V5,
    OMOP_REQ           = VOCABULARY_CONVERSION_TEMP.OMOP_REQ,
    CLICK_DEFAULT      = VOCABULARY_CONVERSION_TEMP.CLICK_DEFAULT,
    AVAILABLE          = VOCABULARY_CONVERSION_TEMP.AVAILABLE,
    URL                = VOCABULARY_CONVERSION_TEMP.URL,
    CLICK_DISABLED     = VOCABULARY_CONVERSION_TEMP.CLICK_DISABLED,
    LATEST_UPDATE      = VOCABULARY_CONVERSION_TEMP.LATEST_UPDATE,
    NAME               = VOCABULARY_CONVERSION_TEMP.NAME

  FROM VOCABULARY_CONVERSION_TEMP
  WHERE vc.VOCABULARY_ID_V4 = VOCABULARY_CONVERSION_TEMP.VOCABULARY_ID_V4;

  INSERT INTO VOCABULARY_CONVERSION AS vc
    SELECT *
    FROM VOCABULARY_CONVERSION_TEMP AS vct
    WHERE vct.VOCABULARY_ID_V4 NOT IN (SELECT VOCABULARY_ID_V4
                                       FROM vocabulary_conversion);

  DROP TABLE VOCABULARY_CONVERSION_TEMP;
  DROP TABLE vocabulary_temp;
END;
$body$
LANGUAGE 'plpgsql'
SECURITY INVOKER
COST 100;