update vocabulary_conversion set name = 'Provider Specialty (American Board of Medical Specialties)' where vocabulary_id_v5 = 'ABMS';
update vocabulary_conversion set name = 'OMOP Standardized Vocabularies' where vocabulary_id_v5 = 'None';
update vocabulary_conversion set name = 'Systematic Nomenclature of Medicine - Clinical Terms (IHTSDO)' where vocabulary_id_v5 = 'SNOMED';
update vocabulary_conversion set name = 'International Classification of Diseases, Ninth Revision, Clinical Modification, Volume 1 and 2 (NCHS)' where vocabulary_id_v5 = 'ICD9CM';
update vocabulary_conversion set name = 'International Classification of Diseases, Ninth Revision, Clinical Modification, Volume 3 (NCHS)' where vocabulary_id_v5 = 'ICD9Proc';
update vocabulary_conversion set name = 'Current Procedural Terminology version 4 (AMA)' where vocabulary_id_v5 = 'CPT4';
update vocabulary_conversion set name = 'Healthcare Common Procedure Coding System (CMS)' where vocabulary_id_v5 = 'HCPCS';
update vocabulary_conversion set name = 'Logical Observation Identifiers Names and Codes (Regenstrief Institute)' where vocabulary_id_v5 = 'LOINC';
update vocabulary_conversion set name = 'National Drug File - Reference Terminology (VA)' where vocabulary_id_v5 = 'NDFRT';
update vocabulary_conversion set name = 'RxNorm (NLM)' where vocabulary_id_v5 = 'RxNorm';
update vocabulary_conversion set name = 'National Drug Code (FDA and manufacturers)' where vocabulary_id_v5 = 'NDC';
update vocabulary_conversion set name = 'Medi-Span Generic Product Identifier (Wolters Kluwer Health)' where vocabulary_id_v5 = 'GPI';
update vocabulary_conversion set name = 'Unified Code for Units of Measure (Regenstrief Institute)' where vocabulary_id_v5 = 'UCUM';
update vocabulary_conversion set name = 'OMOP Gender' where vocabulary_id_v5 = 'Gender';
update vocabulary_conversion set name = 'Race and Ethnicity Code Set (USBC)' where vocabulary_id_v5 = 'Race';
update vocabulary_conversion set name = 'Place of Service Codes for Professional Claims (CMS)' where vocabulary_id_v5 = 'Place of Service';
update vocabulary_conversion set name = 'Medical Dictionary for Regulatory Activities (MSSO)' where vocabulary_id_v5 = 'MedDRA';
update vocabulary_conversion set name = 'Cerner Multum (Cerner)' where vocabulary_id_v5 = 'Multum';
update vocabulary_conversion set name = 'NHS UK Read Codes Version 2 (HSCIC)' where vocabulary_id_v5 = 'Read';
update vocabulary_conversion set name = 'Oxford Medical Information System (OCHP)' where vocabulary_id_v5 = 'OXMIS';
update vocabulary_conversion set name = 'Indications and Contraindications (FDB)' where vocabulary_id_v5 = 'Indication';
update vocabulary_conversion set name = 'Enhanced Therapeutic Classification (FDB)' where vocabulary_id_v5 = 'ETC';
update vocabulary_conversion set name = 'WHO Anatomic Therapeutic Chemical Classification' where vocabulary_id_v5 = 'ATC';
update vocabulary_conversion set name = 'Multilex (FDB)' where vocabulary_id_v5 = 'Multilex';
update vocabulary_conversion set name = 'OMOP Visit' where vocabulary_id_v5 = 'Visit';
update vocabulary_conversion set name = 'VA National Drug File Product (VA)' where vocabulary_id_v5 = 'VA Product';
update vocabulary_conversion set name = 'Standardised MedDRA Queries (MSSO)' where vocabulary_id_v5 = 'SMQ';
update vocabulary_conversion set name = 'VA National Drug File Class (VA)' where vocabulary_id_v5 = 'VA Class';
update vocabulary_conversion set name = 'Legacy OMOP HOI or DOI cohort' where vocabulary_id_v5 = 'Cohort';
update vocabulary_conversion set name = 'International Classification of Diseases, Tenth Revision (WHO)' where vocabulary_id_v5 = 'ICD10';
update vocabulary_conversion set name = 'ICD-10 Procedure Coding System (CMS)' where vocabulary_id_v5 = 'ICD10PCS';
update vocabulary_conversion set name = 'OMOP Drug Exposure Type' where vocabulary_id_v5 = 'Drug Type';
update vocabulary_conversion set name = 'OMOP Condition Occurrence Type' where vocabulary_id_v5 = 'Condition Type';
update vocabulary_conversion set name = 'OMOP Procedure Occurrence Type' where vocabulary_id_v5 = 'Procedure Type';
update vocabulary_conversion set name = 'OMOP Observation Type' where vocabulary_id_v5 = 'Observation Type';
update vocabulary_conversion set name = 'Diagnosis-related group (CMS)' where vocabulary_id_v5 = 'DRG';
update vocabulary_conversion set name = 'Major Diagnostic Categories (CMS)' where vocabulary_id_v5 = 'MDC';
update vocabulary_conversion set name = 'Ambulatory Payment Classification (CMS)' where vocabulary_id_v5 = 'APC';
update vocabulary_conversion set name = 'UB04/CMS1450 Revenue Codes (CMS)' where vocabulary_id_v5 = 'Revenue Code';
update vocabulary_conversion set name = 'OMOP Ethnicity' where vocabulary_id_v5 = 'Ethnicity';
update vocabulary_conversion set name = 'OMOP Death Type' where vocabulary_id_v5 = 'Death Type';
update vocabulary_conversion set name = 'Medical Subject Headings (NLM)' where vocabulary_id_v5 = 'MeSH';
update vocabulary_conversion set name = 'National Uniform Claim Committee Health Care Provider Taxonomy Code Set (NUCC)' where vocabulary_id_v5 = 'NUCC';
update vocabulary_conversion set name = 'Medicare provider/supplier specialty codes (CMS)' where vocabulary_id_v5 = 'Specialty';
update vocabulary_conversion set name = 'Structured Product Labeling (FDA)' where vocabulary_id_v5 = 'SPL';
update vocabulary_conversion set name = 'Clinical Classifications Software for ICD-9-CM (HCUP)' where vocabulary_id_v5 = 'CCS';
update vocabulary_conversion set name = 'OPCS Classification of Interventions and Procedures version 4 (NHS)' where vocabulary_id_v5 = 'OPCS4';
update vocabulary_conversion set name = 'Gemscript (Resip)' where vocabulary_id_v5 = 'Gemscript';
update vocabulary_conversion set name = 'Hospital Episode Statistics Specialty (NHS)' where vocabulary_id_v5 = 'HES Specialty';
update vocabulary_conversion set name = 'OMOP Note Type' where vocabulary_id_v5 = 'Note Type';
update vocabulary_conversion set name = 'OMOP Domain' where vocabulary_id_v5 = 'Domain';
update vocabulary_conversion set name = 'National Patient-Centered Clinical Research Network (PCORI)' where vocabulary_id_v5 = 'PCORNet';
update vocabulary_conversion set name = 'OMOP Observation Period Type' where vocabulary_id_v5 = 'Obs Period Type';
update vocabulary_conversion set name = 'OMOP Visit Type' where vocabulary_id_v5 = 'Visit Type';
update vocabulary_conversion set name = 'OMOP Device Type' where vocabulary_id_v5 = 'Device Type';
update vocabulary_conversion set name = 'OMOP Measurement Type' where vocabulary_id_v5 = 'Meas Type';
update vocabulary_conversion set name = 'International Currency Symbol (ISO 4217)' where vocabulary_id_v5 = 'Currency';
update vocabulary_conversion set name = 'OMOP Relationship' where vocabulary_id_v5 = 'Relationship';
update vocabulary_conversion set name = 'OMOP Vocabulary' where vocabulary_id_v5 = 'Vocabulary';
update vocabulary_conversion set name = 'OMOP Concept Class' where vocabulary_id_v5 = 'Concept Class';
update vocabulary_conversion set name = 'OMOP Cohort Type' where vocabulary_id_v5 = 'Cohort Type';
update vocabulary_conversion set name = 'International Classification of Diseases, Tenth Revision, Clinical Modification (NCHS)' where vocabulary_id_v5 = 'ICD10CM';
update vocabulary_conversion set name = 'Columbia International eHealth Laboratory (Columbia University)' where vocabulary_id_v5 = 'CIEL';
update vocabulary_conversion set name = 'Drug Product Database (Health Canada)' where vocabulary_id_v5 = 'DPD';
update vocabulary_conversion set name = 'Dictionary of Medicines and Devices (NHS)' where vocabulary_id_v5 = 'dm+d';
update vocabulary_conversion set name = 'OMOP Cost Type' where vocabulary_id_v5 = 'Cost Type';
update vocabulary_conversion set name = 'Global Reference Repository (IMS)' where vocabulary_id_v5 = 'GRR';
update vocabulary_conversion set name = 'Disease Analyzer France (IMS)' where vocabulary_id_v5 = 'DA_France';
update vocabulary_conversion set name = 'Public Database of Medications (Social-Sante)' where vocabulary_id_v5 = 'BDPM';
update vocabulary_conversion set name = 'Medicinal Products Information System (DIMDI)' where vocabulary_id_v5 = 'AMIS';
update vocabulary_conversion set name = 'Australian Medicines Terminology (NEHTA)' where vocabulary_id_v5 = 'AMT';
update vocabulary_conversion set name = 'Community Register of Medicinal Products for Human Use (European Commission)' where vocabulary_id_v5 = 'EU Product';
update vocabulary_conversion set name = 'Longitudinal Patient Data Australia (IMS)' where vocabulary_id_v5 = 'LPD_Australia';
update vocabulary_conversion set name = 'Clinical Formulation ID (FDB)' where vocabulary_id_v5 = 'GCN_SEQNO';
update vocabulary_conversion set name = 'Anatomical Classification of Pharmaceutical Products (EphMRA)' where vocabulary_id_v5 = 'EphMRA ATC';
update vocabulary_conversion set name = 'New Form Code (EphMRA)' where vocabulary_id_v5 = 'NFC';
update vocabulary_conversion set name = 'RxNorm Extension (OMOP)' where vocabulary_id_v5 = 'RxNorm Extension';